services:
  - type: web
    name: kawaiihakowaseru
    runtime: static
    plan: free
    autoDeployTrigger: commit


    buildCommand: echo "no build"


    staticPublishPath: ./www

    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html
